backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "home"
        label: "Homepage Content"
        file: "content/home.json"
        fields:
          - {label: "Main Headline", name: "headline", widget: "string", default: "Welcome to my website"}
          - {label: "Sub Text", name: "subtext", widget: "text", default: "This is my website description."}
